[project]
name = "save_webp_avif"
description = "Save as WebP or AVIF in ComfyUI."
version = "0.9"
license = "Unlicense"
dependencies = ["piexif", "pillow", "pillow-avif-plugin"]
keywords = ["avif", "webp", "image-save", "export"]

[project.urls]
Repository = "https://github.com/AlterMann3/save_webp_avif"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "AlterMann3"
DisplayName = "save_webp_avif"
Icon = ""
Tags = ["image", "save", "avif", "webp"] 
